function getPeriodeMinggu(){const input=document.getElementById("tglMulai").value;if(!input)return null;const start=new Date(input+"T00:00:00");start.setDate(start.getDate()-start.getDay());const end=new Date(start);end.setDate(end.getDate()+6);return {start:formatDateISO(start),end:formatDateISO(end)}}

function backupLocal(weekKey,data){try{localStorage.setItem(LOCAL_BACKUP_PREFIX+weekKey,JSON.stringify({weekStart:weekKey,savedAt:new Date().toISOString(),data:data}))}catch(e){console.warn("Local backup gagal:",e)}}
function readLocalBackup(weekKey){try{const raw=localStorage.getItem(LOCAL_BACKUP_PREFIX+weekKey);return raw?JSON.parse(raw):null}catch(e){return null}}
function dataSignature(data){return JSON.stringify((Array.isArray(data)?data:[]).map(normalisasiKaryawan))}

// Cloud client: no browser cache for attendance data, but short in-memory cache for Master.
// This avoids requesting the same Master repeatedly while moving between weeks.
let masterCache=null;
let masterCacheAt=0;
const MASTER_CACHE_TTL=30000;

async function fetchCloudJson(url,options={},attempts=2){let lastError=null;for(let i=0;i<attempts;i++){try{const separator=url.includes('?')?'&':'?';const res=await fetch(url+separator+`_ts=${Date.now()}_${i}`,{...options,cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const text=await res.text();if(!text.trim())throw new Error('Respons cloud kosong.');let result;try{result=JSON.parse(text)}catch(_){throw new Error('Respons cloud bukan JSON yang valid.')}return result}catch(e){lastError=e;if(i<attempts-1)await new Promise(r=>setTimeout(r,350))}}throw lastError||new Error('Cloud tidak dapat dihubungi.')}

async function ambilMasterAktif(force=false){const now=Date.now();if(!force&&masterCache&&now-masterCacheAt<MASTER_CACHE_TTL)return masterCache;const result=await fetchCloudJson(`${CONFIG.SCRIPT_URL}?action=master`);if(!result||result.success!==true||!Array.isArray(result.data))throw new Error(result?.message||"Master karyawan tidak dapat dimuat.");masterCache=result.data.filter(k=>String(k.status||"AKTIF").toUpperCase()==="AKTIF");masterCacheAt=now;return masterCache}

async function buatKaryawanMingguBaruDariMaster(){const aktif=await ambilMasterAktif();if(!aktif.length)throw new Error("Belum ada karyawan AKTIF di Master Karyawan. Minggu baru tidak dibuat.");return aktif.map(k=>buatStrukturKaryawan(String(k.nama||""),Number(k.gajiPokok)||0,null,String(k.id||"")))}

function mingguSekarangStart(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-d.getDay());return formatDateISO(d)}

async function sinkronkanMasterKeMingguAktif(periode,cloudData){if(periode.start < mingguSekarangStart())return {data:cloudData,changed:false};const aktif=await ambilMasterAktif();if(!aktif.length)return {data:cloudData,changed:false};const existingIds=new Set(cloudData.map(k=>String(k.masterId||k.employeeId||"")).filter(Boolean));const existingNames=new Set(cloudData.filter(k=>!String(k.masterId||k.employeeId||"")).map(k=>String(k.nama||"").trim().toLowerCase()).filter(Boolean));const additions=[];aktif.forEach(m=>{const id=String(m.id||"");const name=String(m.nama||"").trim().toLowerCase();if((id&&existingIds.has(id))||(!id&&name&&existingNames.has(name)))return;additions.push(buatStrukturKaryawan(String(m.nama||""),Number(m.gajiPokok)||0,null,id))});if(!additions.length)return {data:cloudData,changed:false};return {data:[...cloudData,...additions],changed:true}}

function updatePeriodeTanggal(autoLoad=false){const p=getPeriodeMinggu();if(!p)return;clearTimeout(timerSave);timerSave=null;pendingSave=false;document.getElementById("tglMulai").value=p.start;document.getElementById("tglSelesai").value=p.end;const start=new Date(p.start+"T00:00:00");HARI.forEach((h,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);document.getElementById("date-"+h).innerText=d.toLocaleDateString("id-ID",{day:"numeric",month:"short"})});document.getElementById("periodeAktif").innerText=`PERIODE AKTIF: ${formatTanggalIndonesia(p.start)} — ${formatTanggalIndonesia(p.end)}`;if(typeof updateStatusNavigasi==='function')updateStatusNavigasi();if(autoLoad)muatDataDariCloud()}
function pindahMinggu(delta){const p=getPeriodeMinggu();if(!p)return;clearTimeout(timerSave);timerSave=null;pendingSave=false;const d=new Date(p.start+"T00:00:00");d.setDate(d.getDate()+delta*7);document.getElementById("tglMulai").value=formatDateISO(d);updatePeriodeTanggal(true)}

async function bacaMingguDariCloud(periode){const result=await fetchCloudJson(`${CONFIG.SCRIPT_URL}?action=get&weekStart=${encodeURIComponent(periode.start)}`,{},2);if(Array.isArray(result))return result;if(!result||result.success!==true)throw new Error(result?.message||"Respons cloud tidak valid");if(result.weekStart&&result.weekStart!==periode.start)throw new Error("Cloud mengembalikan periode yang berbeda.");if(!Array.isArray(result.data))throw new Error("Format data cloud tidak valid.");return result.data}

async function verifikasiSimpanCloud(periode,expectedData){let lastError=null;for(let i=0;i<2;i++){try{const cloudData=await bacaMingguDariCloud(periode);if(dataSignature(cloudData)===dataSignature(expectedData))return cloudData;lastError=new Error("Data cloud belum sama dengan data terbaru.")}catch(e){lastError=e}if(i<1)await new Promise(r=>setTimeout(r,500))}throw lastError||new Error("Verifikasi cloud gagal.")}

async function muatDataDariCloud(){if(loadingWeek)return;loadingWeek=true;cloudReadyForWeek=false;pendingSave=false;const p=getPeriodeMinggu();if(!p){loadingWeek=false;return}setStatusSync("loading",`Mengambil data ${p.start} s/d ${p.end}...`);try{const cloudData=await bacaMingguDariCloud(p);if(cloudData.length>0){let displayData=cloudData;try{const synced=await sinkronkanMasterKeMingguAktif(p,cloudData);displayData=synced.data;dataKaryawan=displayData.map(normalisasiKaryawan);loadedWeekKey=p.start;cloudReadyForWeek=true;backupLocal(p.start,dataKaryawan);if(synced.changed){setStatusSync("loading",`Menambahkan ${dataKaryawan.length-cloudData.length} karyawan Master...`);renderTabel();const ok=await simpanDataKeCloudDirect(true,p,JSON.parse(JSON.stringify(dataKaryawan)));if(!ok)setStatusSync("warning","Cloud absensi berhasil dimuat, tetapi sinkronisasi Master menunggu cloud siap.")}else{setStatusSync("active",`Cloud aktif — ${formatTanggalIndonesia(p.start)} s/d ${formatTanggalIndonesia(p.end)}`);renderTabel()}}catch(masterError){dataKaryawan=cloudData.map(normalisasiKaryawan);loadedWeekKey=p.start;cloudReadyForWeek=true;backupLocal(p.start,dataKaryawan);setStatusSync("warning",`Cloud aktif — Master belum tersinkron (${masterError.message||"gagal dimuat"}).`);renderTabel()}return}
dataKaryawan=await buatKaryawanMingguBaruDariMaster();loadedWeekKey=p.start;cloudReadyForWeek=true;backupLocal(p.start,dataKaryawan);setStatusSync("loading",`Minggu baru — ${dataKaryawan.length} karyawan dari Master...`);renderTabel();const created=await simpanDataKeCloudDirect(true,p,JSON.parse(JSON.stringify(dataKaryawan)));if(!created)throw new Error("Minggu baru berhasil disiapkan, tetapi penyimpanan cloud belum terverifikasi.")
}catch(e){console.error(e);cloudReadyForWeek=false;pendingSave=false;const localBackup=readLocalBackup(p.start);if(localBackup&&Array.isArray(localBackup.data)){dataKaryawan=localBackup.data.map(normalisasiKaryawan);setStatusSync("error",`Cloud gagal — backup lokal ditampilkan untuk ${formatTanggalIndonesia(p.start)}. Perubahan dikunci sampai cloud pulih. (${e.message||"error tidak diketahui"})`);renderTabel()}else{setStatusSync("error",`Cloud gagal dimuat. Data TIDAK diubah dan TIDAK disimpan ulang. ${e.message||""}`)}}finally{loadingWeek=false}}

function pemicuAutoSave(){renderTabel();clearTimeout(timerSave);const p=getPeriodeMinggu();if(!p||!cloudReadyForWeek||loadedWeekKey!==p.start){setStatusSync("error","Cloud belum siap. Perubahan TIDAK disimpan untuk mencegah kehilangan data.");return}const snapshot=JSON.parse(JSON.stringify(dataKaryawan));backupLocal(p.start,snapshot);pendingSave=true;setStatusSync("loading","Perubahan menunggu disimpan...");timerSave=setTimeout(()=>simpanDataKeCloudDirect(false,p,snapshot),600)}

async function simpanDataKeCloudDirect(silent=false,periodeOverride=null,dataOverride=null){const p=periodeOverride||getPeriodeMinggu();if(!p)return false;if(!cloudReadyForWeek||loadedWeekKey!==p.start){setStatusSync("error","Cloud belum siap. Penyimpanan dibatalkan agar data lama tidak tersentuh.");return false}const payloadData=dataOverride||dataKaryawan;if(!Array.isArray(payloadData)||payloadData.length===0){setStatusSync("error","Penyimpanan dibatalkan: data kosong. Data lama tidak disentuh.");pendingSave=false;return false}if(saveInFlight){queuedSave={silent,periode:{start:p.start,end:p.end},data:JSON.parse(JSON.stringify(payloadData))};pendingSave=true;setStatusSync("loading","Penyimpanan sebelumnya masih berjalan. Perubahan terbaru diantrikan...");return false}saveInFlight=true;let success=false;let next=null;const safetyBackup=JSON.parse(JSON.stringify(payloadData));backupLocal(p.start,safetyBackup);const payload={action:"save",weekStart:p.start,weekEnd:p.end,data:payloadData};try{if(!silent)setStatusSync("loading",`Menyimpan ${formatTanggalIndonesia(p.start)} s/d ${formatTanggalIndonesia(p.end)}...`);await fetch(CONFIG.SCRIPT_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});await verifikasiSimpanCloud(p,payloadData);pendingSave=false;success=true;cloudReadyForWeek=true;setStatusSync("active",`Tersimpan & terverifikasi — ${formatTanggalIndonesia(p.start)} s/d ${formatTanggalIndonesia(p.end)}`)}catch(e){console.error(e);pendingSave=false;setStatusSync("error","Penyimpanan belum terverifikasi. Backup lokal dipertahankan dan data cloud lama tidak dianggap aman tertimpa.")}finally{saveInFlight=false;next=queuedSave;queuedSave=null}if(next)return simpanDataKeCloudDirect(next.silent,next.periode,next.data);return success}
