(function(){
  function escapeText(v){return typeof escapeHtml==='function'?escapeHtml(v):String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function injectStyles(){if(document.getElementById('employeeSidebarStyles'))return;const s=document.createElement('style');s.id='employeeSidebarStyles';s.textContent=`
    .pp-nav-label{font-size:10px;font-weight:800;letter-spacing:.12em;color:#94a3b8;padding:10px 12px 6px;text-transform:uppercase}
    .pp-nav-button{width:100%;border:0;background:transparent;font:inherit;text-align:left;cursor:pointer}
    .pp-nav-button:hover{background:#f1f5f9}.pp-sidebar-divider{height:1px;background:#e2e8f0;margin:18px 4px}
    .employee-data-modal{max-width:720px}.employee-data-summary{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:0 0 16px}
    .employee-data-summary>div{background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:12px 14px}.employee-data-summary small{display:block;color:#64748b;font-size:11px}.employee-data-summary strong{display:block;margin-top:3px;color:#0f172a;font-size:16px}
    .employee-data-actions{display:flex;gap:10px;margin-bottom:14px}.employee-data-actions .btn{flex:1}
    .employee-manual-form{display:none;background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:14px;margin-bottom:14px}
    .employee-manual-form.show{display:grid;grid-template-columns:1fr 1fr;gap:8px 12px}.employee-manual-form label:not(.master-enroll-option){font-size:11px;font-weight:700;color:#475569}.employee-manual-form input{min-width:0}.employee-manual-form .master-enroll-option{grid-column:1/-1}.employee-manual-form .btn{grid-column:1/-1}
    .employee-data-list{display:grid;gap:8px;max-height:46vh;overflow:auto}.employee-data-row{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid #e2e8f0;border-radius:12px;padding:11px 13px;background:#fff}.employee-data-row strong{display:block;color:#0f172a}.employee-data-row small{display:block;color:#64748b;margin-top:2px}.employee-data-row .employee-row-actions{display:flex;align-items:center;gap:8px;flex-shrink:0}.employee-data-row .btn.mini{white-space:nowrap}
    @media(max-width:700px){.employee-data-summary{grid-template-columns:1fr}.employee-manual-form.show{grid-template-columns:1fr}.employee-data-actions{flex-direction:column}.employee-data-row{align-items:flex-start;flex-direction:column}.employee-data-row .employee-row-actions{width:100%}.employee-data-row .employee-row-actions .btn{flex:1}}
  `;document.head.appendChild(s)}
  function modal(){return document.getElementById('employeeDataModal')}
  function render(){const list=document.getElementById('employeeDataList');const count=document.getElementById('employeeDataCount');const period=document.getElementById('employeeDataPeriod');if(!list)return;if(count)count.textContent=String((window.dataKaryawan||[]).length);if(period&&typeof getPeriodeMinggu==='function'){const p=getPeriodeMinggu();period.textContent=p?`${formatTanggalIndonesia(p.start)} — ${formatTanggalIndonesia(p.end)}`:'-'}const rows=window.dataKaryawan||[];if(!rows.length){list.innerHTML='<div class="master-empty">Belum ada karyawan pada periode ini.</div>';return}list.innerHTML=rows.map(k=>`<div class="employee-data-row"><div><strong>${escapeText(k.nama)}</strong><small>${formatRupiah(k.gajiPokok)}/hari · ${escapeText(k.masterId||'Manual')}</small></div><div class="employee-row-actions"><button class="btn secondary mini" type="button" onclick="tutupDataKaryawan();document.getElementById('payrollSection')?.scrollIntoView({behavior:'smooth',block:'start'})">Lihat Payroll</button></div></div>`).join('')}
  window.bukaDataKaryawan=function(){injectStyles();const m=modal();if(!m)return;m.classList.add('show');m.setAttribute('aria-hidden','false');const manual=document.querySelector('.employee-manual-form');if(manual)manual.classList.remove('show');render()};
  window.tutupDataKaryawan=function(){const m=modal();if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true')};
  window.fokusTambahManual=function(){const manual=document.querySelector('.employee-manual-form');if(!manual)return;manual.classList.add('show');setTimeout(()=>document.getElementById('modalNamaKaryawan')?.focus(),50)};
  window.tambahKaryawanDariModal=function(){const n=document.getElementById('modalNamaKaryawan'),g=document.getElementById('modalGajiPokok'),en=document.getElementById('modalDaftarKeMaster');const targetN=document.getElementById('namaKaryawan'),targetG=document.getElementById('gajiPokok'),targetEn=document.getElementById('daftarKeMaster');if(!n||!g||!targetN||!targetG)return;targetN.value=n.value;targetG.value=g.value;if(targetEn&&en)targetEn.checked=en.checked;tambahKaryawan().then?.(()=>{render()});setTimeout(render,1000)};
  window.addEventListener('DOMContentLoaded',()=>{injectStyles();const master=document.getElementById('masterSection');if(master)master.style.display='none';const addCard=document.querySelector('.pp-add-card');if(addCard)addCard.style.display='none';const old=document.querySelector('.pp-nav a[href="#masterSection"]');if(old)old.style.display='none';const m=modal();if(m){m.addEventListener('click',e=>{if(e.target===m)tutupDataKaryawan()})}});
})();
