function kontrolHari(k,h){const a=k.absensi[h];return `<label class="check"><input type="checkbox" ${a.hadir?"checked":""} onchange="updateAbsensi('${k.id}','${h}','hadir',this.checked)"> Hadir</label><label class="check half"><input type="checkbox" ${a.setengahHari?"checked":""} ${!a.hadir?"disabled":""} onchange="updateAbsensi('${k.id}','${h}','setengahHari',this.checked)"> ½ Hari</label><div class="time"><span>Lembur</span><input type="number" min="0" value="${a.jamLembur||0}" ${!a.hadir?"disabled":""} onchange="updateAbsensi('${k.id}','${h}','jamLembur',this.value)"></div><div class="time"><span>Telat</span><input type="number" min="0" value="${a.jamTelat||0}" ${!a.hadir?"disabled":""} onchange="updateAbsensi('${k.id}','${h}','jamTelat',this.value)"></div>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#039;"}[m]))}
function toggleKaryawanCard(id){const body=document.getElementById(`employee-body-${id}`),card=document.getElementById(`employee-card-${id}`),icon=document.getElementById(`employee-toggle-${id}`);if(!body)return;const wasOpen=card.classList.contains("is-open");document.querySelectorAll(".karyawan-card.is-open").forEach(c=>{c.classList.remove("is-open");const b=c.querySelector(".karyawan-card-body");const i=c.querySelector(".employee-toggle-icon");if(b)b.hidden=true;if(i)i.textContent="▼"});if(!wasOpen){card.classList.add("is-open");body.hidden=false;if(icon)icon.textContent="▲"}}
function toggleDesktopAbsensi(id){const row=document.getElementById(`desktop-detail-${id}`);const btn=document.getElementById(`desktop-detail-btn-${id}`);if(!row)return;const open=!row.hidden;row.hidden=open;if(btn){btn.textContent=open?"▸ Detail Absen":"▾ Tutup Detail";btn.classList.toggle("is-open",!open)}}
function updatePremiumKpis(grand,totalHadir,totalLembur,totalTelat){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('kpiKaryawan',dataKaryawan.length);set('kpiHadir',totalHadir);set('kpiLembur',totalLembur);set('kpiTelat',totalTelat);set('kpiPayroll',formatRupiah(grand))}
function renderTabel(){
  const pos=window.scrollY||window.pageYOffset||document.documentElement.scrollTop||0;
  const openIds=Array.from(document.querySelectorAll(".karyawan-card.is-open")).map(c=>c.id.replace(/^employee-card-/,'')).filter(Boolean);
  const desktopOpenIds=Array.from(document.querySelectorAll(".desktop-detail-row:not([hidden])")).map(r=>r.id.replace(/^desktop-detail-/,'')).filter(Boolean);
  const activeElement=document.activeElement;const activeId=activeElement?.id||null;
  const desktop=document.getElementById("bodyTabelDesktop"),mobile=document.getElementById("mobileCardsContainer");
  desktop.innerHTML="";mobile.innerHTML="";let grand=0,totalHadir=0,totalLembur=0,totalTelat=0;
  dataKaryawan.forEach(k=>{
    const c=hitung(k);grand+=c.total;totalHadir+=c.hadir;totalLembur+=c.lembur;totalTelat+=c.telat;
    let row=`<tr class="payroll-summary-row align-middle"><td class="employee-name-cell"><div class="font-bold text-slate-800 truncate">${esc(k.nama)}</div></td><td class="font-semibold whitespace-nowrap">${formatRupiah(k.gajiPokok)}</td><td><strong>${c.hadir}</strong> Hari</td><td><strong>${c.lembur} jam</strong><br><small style="color:#16a34a">+${formatRupiah(c.uangLembur)}</small></td><td><strong>${c.telat} jam</strong><br><small style="color:#dc2626">-${formatRupiah(c.potTelat)}</small></td><td><input class="money-input" type="number" value="${k.bonus||0}" onchange="updateNilaiLain('${k.id}','bonus',this.value)" aria-label="Bonus ${esc(k.nama)}"></td><td><input class="money-input" type="number" value="${k.kasbon||0}" onchange="updateNilaiLain('${k.id}','kasbon',this.value)" aria-label="Kasbon ${esc(k.nama)}"></td><td class="payment-cell">${paymentButtonHtml(k)}</td><td class="actions-cell"><button id="desktop-detail-btn-${k.id}" class="btn secondary mini desktop-absensi-btn" type="button" onclick="toggleDesktopAbsensi('${k.id}')">▸ Detail Absen</button></td><td class="actions-cell"><button class="btn secondary mini" type="button" onclick="cetakSlipGaji('${k.id}')" title="Cetak slip gaji" aria-label="Cetak slip gaji ${esc(k.nama)}">🖨️ Print</button></td><td class="actions-cell"><button class="btn danger mini" type="button" onclick="hapusKaryawan('${k.id}')" title="Hapus karyawan" aria-label="Hapus ${esc(k.nama)}">Hapus</button></td></tr>`;
    row+=`<tr id="desktop-detail-${k.id}" class="desktop-detail-row" hidden><td colspan="11"><div class="desktop-absensi-detail"><div class="desktop-detail-title"><strong>Absensi 7 Hari — ${esc(k.nama)}</strong><span>Klik ceklis atau ubah jam langsung</span></div><div class="desktop-day-grid">`;
    HARI.forEach(h=>{const dateSub=document.getElementById("date-"+h)?.innerText||"";row+=`<div class="desktop-day-box"><div class="desktop-day-title"><span>${h.toUpperCase()}</span><small>${dateSub}</small></div><div class="day-inputs">${kontrolHari(k,h)}</div></div>`});
    row+=`</div></div></td></tr>`;
    desktop.innerHTML+=row;
    let card=`<div class="karyawan-card" id="employee-card-${k.id}"><div class="karyawan-card-header"><button class="employee-toggle" type="button" onclick="toggleKaryawanCard('${k.id}')"><span><strong>${esc(k.nama)}</strong> <span style="font-size:11px;opacity:.8">(${formatRupiah(k.gajiPokok)}/hr)</span></span><span class="employee-toggle-icon" id="employee-toggle-${k.id}">▼</span></button><div class="employee-card-actions"><button class="btn secondary mini" onclick="cetakSlipGaji('${k.id}')">🖨️ Slip</button><button class="btn danger mini" onclick="hapusKaryawan('${k.id}')">Hapus</button></div></div><div class="karyawan-card-body" id="employee-body-${k.id}" hidden><div class="mobile-day-grid">`;
    HARI.forEach(h=>{const dateSub=document.getElementById("date-"+h)?.innerText||"";card+=`<div class="mobile-day-box"><div class="mobile-day-title"><span>${h.toUpperCase()}</span><span style="font-weight:normal;color:#64748b">${dateSub}</span></div><div class="day-inputs">${kontrolHari(k,h)}</div></div>`});
    card+=`</div><div class="mobile-summary-box"><div>Hadir: <strong>${c.hadir} Hari</strong></div><div>Bonus: <input type="number" style="width:65px;padding:2px;height:22px" value="${k.bonus||0}" onchange="updateNilaiLain('${k.id}','bonus',this.value)"></div><div>Lembur: <span style="color:#16a34a">+${formatRupiah(c.uangLembur)}</span></div><div>Kasbon: <input type="number" style="width:65px;padding:2px;height:22px" value="${k.kasbon||0}" onchange="updateNilaiLain('${k.id}','kasbon',this.value)"></div><div>Telat: <span style="color:#dc2626">-${formatRupiah(c.potTelat)}</span></div><div class="mobile-payment-wrap">${paymentButtonHtml(k)}</div><div style="font-weight:bold;color:#15803d;align-self:center">Gaji: ${formatRupiah(c.total)}</div></div></div></div>`;
    mobile.innerHTML+=card;
  });
  document.getElementById("grandTotalGaji").innerText=formatRupiah(grand);
  updatePremiumKpis(grand,totalHadir,totalLembur,totalTelat);
  if(typeof renderStatusPembayaran==="function")renderStatusPembayaran();
  openIds.forEach(id=>{const card=document.getElementById(`employee-card-${id}`),body=document.getElementById(`employee-body-${id}`),icon=document.getElementById(`employee-toggle-${id}`);if(card&&body){card.classList.add("is-open");body.hidden=false;if(icon)icon.textContent="▲"}});
  desktopOpenIds.forEach(id=>{const row=document.getElementById(`desktop-detail-${id}`),btn=document.getElementById(`desktop-detail-btn-${id}`);if(row){row.hidden=false;if(btn){btn.textContent="▾ Tutup Detail";btn.classList.add("is-open")}}});
  requestAnimationFrame(()=>{window.scrollTo({top:pos,left:0,behavior:"instant"});if(activeId){const next=document.getElementById(activeId);if(next&&document.activeElement!==next)try{next.focus({preventScroll:true})}catch(e){}}});
}